#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Rtree
Version  : 0.9.7
Release  : 7
URL      : https://files.pythonhosted.org/packages/ff/6f/1dcfc62cd3f0347a67b5e302250271837860ea4973c5df512dc6347fb070/Rtree-0.9.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/ff/6f/1dcfc62cd3f0347a67b5e302250271837860ea4973c5df512dc6347fb070/Rtree-0.9.7.tar.gz
Summary  : R-Tree spatial index for Python GIS
Group    : Development/Tools
License  : MIT
Requires: Rtree-python = %{version}-%{release}
Requires: Rtree-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : wheel

%description
------------------------------------------------------------------------------
        
        `Rtree`_ is a `ctypes`_ Python wrapper of `libspatialindex`_ that provides a 
        number of advanced spatial indexing features for the spatially curious Python

%package python
Summary: python components for the Rtree package.
Group: Default
Requires: Rtree-python3 = %{version}-%{release}
Provides: rtree-python

%description python
python components for the Rtree package.


%package python3
Summary: python3 components for the Rtree package.
Group: Default
Requires: python3-core
Provides: pypi(rtree)

%description python3
python3 components for the Rtree package.


%prep
%setup -q -n Rtree-0.9.7
cd %{_builddir}/Rtree-0.9.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1623429603
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
